# Generated by Django 3.2.5 on 2021-10-08 11:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='restaurant/default.jpg', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
