# Generated by Django 3.2.5 on 2021-10-08 13:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='restaurant/default.jpeg', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
