# Generated by Django 3.2.5 on 2021-07-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_restaurant_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestaurantrating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
