# Generated by Django 3.2.5 on 2021-07-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userrestaurantrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='contact',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrestaurantrating',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to='api.restaurant'),
        ),
    ]
