# Generated by Django 3.2.5 on 2021-07-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210724_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestaurantrating',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
