# Generated by Django 3.2.5 on 2021-07-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userrestaurantrating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestaurantrating',
            name='date',
            field=models.DateField(),
        ),
    ]
