# Generated by Django 3.2.5 on 2021-07-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userrestaurantrating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestaurantrating',
            name='date',
            field=models.PositiveBigIntegerField(),
        ),
    ]
